export enum PlayerRoleEnum {
  NOT_SELECTED = 'NOT_SELECTED',
  VILLAGEOIS = 'VILLAGEOIS',
  LOUP_GAROU = 'LOUP_GAROU',
  CHASSEUR = 'CHASSEUR',
  CUPIDON = 'CUPIDON',
  PETITE_FILLE = 'PETITE_FILLE',
  SORCIERE = 'SORCIERE',
  VOLEUR = 'VOLEUR',
  VOYANTE = 'VOYANTE',
  JOUEUR_FLUTE = 'JOUEUR_FLUTE',
  CORBEAU = 'CORBEAU',
}
