import { PlayerRole } from '@/types/player-role';

export const ROLE_NAMES: Record<PlayerRole, string> = {
  [PlayerRole.NOT_SELECTED]: '',
  [PlayerRole.VILLAGEOIS]: 'Villageois',
  [PlayerRole.LOUP_GAROU]: 'Loup-garou',
  [PlayerRole.CHASSEUR]: 'Chasseur',
  [PlayerRole.CUPIDON]: 'Cupidon',
  [PlayerRole.PETITE_FILLE]: 'Petite fille',
  [PlayerRole.SORCIERE]: 'Sorcière',
  [PlayerRole.VOYANTE]: 'Voyante',
  [PlayerRole.JOUEUR_FLUTE]: 'Joueur de flûte',
  [PlayerRole.CORBEAU]: 'Corbeau',
  [PlayerRole.ENFANT_SAUVAGE]: 'Enfant sauvage',
  [PlayerRole.SALVATEUR]: 'Salvateur',
  [PlayerRole.GRAND_MECHANT_LOUP]: 'Grand méchant loup',
  [PlayerRole.MONTREUR_OURS]: "Montreur d'ours",
  [PlayerRole.RENARD]: 'Renard',
  [PlayerRole.CHIEN_LOUP]: 'Chien-loup',
  [PlayerRole.SOEUR]: 'Sœur',
  [PlayerRole.FRERE]: 'Frère',
  [PlayerRole.LOUP_BLANC]: 'Loup-garou blanc',
  [PlayerRole.VOLEUR]: 'Voleur',
  [PlayerRole.ANGE]: 'Ange',
  [PlayerRole.ANCIEN]: 'Ancien',
  [PlayerRole.IDIOT]: 'Idiot du village',
  [PlayerRole.CHEVALIER]: "Chevalier à l'épée rouillée",
  [PlayerRole.BOUC]: 'Bouc émissaire',
  [PlayerRole.SECTAIRE]: 'Abominable sectaire',
  [PlayerRole.PERE_LOUPS]: 'Infect père des loups',
};
