import { Round } from '@/types/round';

export const ROUND_NAMES: Record<Round, string> = {
  [Round.CUPIDON]: 'Tir de Cupidon',
  [Round.VOYANTE]: 'Vision de la voyante',
  [Round.AMOUREUX]: 'Découverte des amoureux',
  [Round.LOUP_GAROU]: 'Attaque des loups-garous',
  [Round.SORCIERE_HEALTH]: 'Soin de la sorcière',
  [Round.SORCIERE_KILL]: 'Potion de mort de la sorcière',
  [Round.VILLAGEOIS]: 'Vote des villageois',
  [Round.CAPITAINE]: 'Election du capitaine',
  [Round.CHASSEUR]: 'Tir du chasseur',
  [Round.JOUEUR_FLUTE]: 'Charme du joueur de flûte',
  [Round.CHARMED]: 'Découverte des charmés',
  [Round.CORBEAU]: 'Accusation du corbeau',
  [Round.ENFANT_SAUVAGE]: "Modèle de l'enfant sauvage",
  [Round.SALVATEUR]: 'Protection du salvateur',
  [Round.GRAND_MECHANT_LOUP]: 'Attaque du grand méchant loup',
  [Round.MONTREUR_OURS]: "Grognement de l'ours",
  [Round.RENARD]: 'Reniflement du renard',
  [Round.CHIEN_LOUP]: 'Choix du chien-loup',
  [Round.SOEURS]: 'Découverte des 2 sœurs',
  [Round.FRERES]: 'Découverte des 3 frères',
  [Round.LOUP_BLANC]: 'Attaque du loup blanc',
  [Round.VOLEUR]: 'Echange du voleur',
  [Round.BOUC]: 'Choix des votants du bouc émissaire',
  [Round.SECTAIRE]: 'Définition des groupes',
  [Round.PERE_LOUPS]: 'Infection par le père des loups',
};
