import { RoundEnum } from '../enums/round.enum';

export const ROUNDS_ORDER_CONFIG: RoundEnum[] = [
  RoundEnum.SECTAIRE,
  RoundEnum.VOLEUR,
  RoundEnum.CUPIDON,
  RoundEnum.VOYANTE,
  RoundEnum.RENARD,
  RoundEnum.AMOUREUX,
  RoundEnum.SOEURS,
  RoundEnum.FRERES,
  RoundEnum.ENFANT_SAUVAGE,
  RoundEnum.CORBEAU,
  RoundEnum.SALVATEUR,
  RoundEnum.CHIEN_LOUP,
  RoundEnum.LOUP_GAROU,
  RoundEnum.LOUP_BLANC,
  RoundEnum.PERE_LOUPS,
  RoundEnum.GRAND_MECHANT_LOUP,
  RoundEnum.SORCIERE_HEALTH,
  RoundEnum.SORCIERE_KILL,
  RoundEnum.JOUEUR_FLUTE,
  RoundEnum.CHARMED,
  RoundEnum.MONTREUR_OURS,
  RoundEnum.CAPITAINE,
  RoundEnum.VILLAGEOIS,
];
