export enum PlayerRoleEnum {
  VILLAGEOIS = 'VILLAGEOIS',
  LOUP_GAROU = 'LOUP_GAROU',
  CHASSEUR = 'CHASSEUR',
  CUPIDON = 'CUPIDON',
  PETITE_FILLE = 'PETITE_FILLE',
  SORCIERE = 'SORCIERE',
  VOLEUR = 'VOLEUR',
  VOYANTE = 'VOYANTE',
}
